version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Port du backend
    environment:
      DB_HOST: db
      DB_USER: wikiuser
      DB_PASSWORD: wikipwd
      DB_NAME: wikidb
      DB_PORT: 5432
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD: wikipwd
      POSTGRES_DB: wikidb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: